// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID              string   `json:"id"`
	Name            string   `json:"name"`
	Diaries         []*Diary `json:"diaries"`
	NumberOfDiaries int      `json:"number_of_diaries"`
}

func (Author) IsEntity() {}

type Diary struct {
	ID      string  `json:"id"`
	Author  *Author `json:"author"`
	Content string  `json:"content"`
}

func (Diary) IsEntity() {}
