// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID string `json:"id"`
}

func (Author) IsEntity() {}

type Diary struct {
	ID     string   `json:"id"`
	Musics []*Music `json:"musics"`
}

func (Diary) IsEntity() {}

type DiaryMusicLink struct {
	MusicID string `json:"music_id"`
	DiaryID string `json:"diary_id"`
}

type Music struct {
	ID     string  `json:"id"`
	Author *Author `json:"author"`
	Name   string  `json:"name"`
	Length string  `json:"length"`
}

func (Music) IsEntity() {}
